server:
  port: 5000

spring:
  application:
    name: aroma-delivery

  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5435/aromadelivery
    url: jdbc:postgresql://aromadelivery.cd60cc24wdbw.us-east-1.rds.amazonaws.com:5432/aromadelivery
    username: aromadelivery
    password: aromadelivery2024
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
      logging:
        level:
          org.hibernate.SQL: DEBUG
          org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration

viacep.integration.uri: https://viacep.com.br/ws