### Autenticar como cliente
POST {{host}}/autenticacao/login
Content-Type: application/json

{
  "login": "rocha.wellen",
  "senha": "teste"
}

> {% client.global.set("jwt_token", response.body.token); %}


### Autenticar como administrador
POST {{host}}/autenticacao/login
Content-Type: application/json

{
  "login": "admin@gmail.com",
  "senha": "teste"
}

> {% client.global.set("jwt_token", response.body.token); %}