### Adicionar item no carrinho
POST {{host}}/carrinho
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "produtoId": 1,
  "quantidade": 1,
  "observacao": "item adicionado",
  "tamanhoCopo": "GRANDE"
}

### Alterar itens do carrinho
PUT {{host}}/carrinho
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "id": 4,
  "carrinhoId": 1,
  "produtoId": 1,
  "quantidade": 1,
  "observacao": "item adicionado",
  "tamanhoCopo": "PEQUENO"
}

### Deletar itens no carrinho
DELETE {{host}}/carrinho/1/itens/5
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

