### Criar endereço
POST {{host}}/cartoes
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "numero": "5440 8046 5056 8738",
  "titular": "Wellen Ramos Rodrigues Rocha",
  "validadeMes": 12,
  "validadeAno": 2025,
  "cvv": "228"
}
