### Criar produto adicional
POST {{host}}/produtos
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "nome": "Nutella",
  "descricao": "A Original!",
  "preco": 4.50,
  "categoriaId": 2,
  "adicionais": []
}

### Criar produto com adicionais
POST {{host}}/produtos
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "nome": "Chocolate Quente 1",
  "descricao": "Chocolate quente europeu bem cremoso, pra aquecer o coração!",
  "preco": 23.00,
  "categoriaId": 2,
  "adicionais": [1]
}

### Alterar produto
PUT {{host}}/produtos
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "id": 2,
  "nome": "Chocolate Quente",
  "descricao": "Chocolate quente europeu bem cremoso, pra aquecer o coração!",
  "preco": 23.00,
  "categoriaId": 2,
  "adicionais": [1]
}

### Buscar produto
GET {{host}}/produtos/2
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### Deletar produto
DELETE {{host}}/produtos/2
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### Buscar produto por categoria
GET {{host}}/produtos/categoria/2
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### Buscar produto por nome
GET {{host}}/produtos/categoria/1/todos?nome=Cafe
Content-Type: application/json
Authorization: Bearer {{jwt_token}}v

### Publicar produto
PUT {{host}}/produtos/1/publicar
Content-Type: application/json
Authorization: Bearer {{jwt_token}}