### Criar produto
POST {{host}}/produtos
Content-Type: application/json

{
  "nome": "Café 3 corações",
  "descricao": "",
  "preco": 8.00,
  "categoriaId": 2
}

### Alterar produto
PUT {{host}}/produtos
Content-Type: application/json

{
  "id": 3,
  "nome": "Café do Sítio",
  "descricao": "",
  "preco": 13.00,
  "categoriaId": 1
}

### Buscar produto
GET {{host}}/produtos/1
Content-Type: application/jsonImple

### Deletar produto
DELETE {{host}}/produtos/2
Content-Type: application/json

### Buscar produto por categoria
GET {{host}}/produtos/categoria/1
Content-Type: application/json

### Buscar produto por nome
GET {{host}}/produtos/categoria/1/todos?nome=Cafe
Content-Type: application/json