### Criar usuario
POST {{host}}/usuarios
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "nome": "Wellen Ramos Rodrigues Rocha",
  "email": "admin@gmail.com",
  "senha": "teste"
}

### Atualiza usuario
PUT {{host}}/usuarios
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "id": 4,
  "nome": "Fabio Junior Rodrigues",
  "email": "fabiojunior@gmail.com",
  "senha": "teste@124"
}

### Obter usuario por id
GET {{host}}/usuarios/2
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### Obter usuario por id
DELETE {{host}}/usuarios/4
Content-Type: application/json
Authorization: Bearer {{jwt_token}}