### Criar usuario
POST {{host}}/usuarios
Content-Type: application/json

{
  "nome": "Wellen Ramos Rodrigues Rocha",
  "email": "wellen.rocha@gmail.com",
  "senha": "teste"
}

### Atualiza usuario
PUT {{host}}/usuarios
Content-Type: application/json

{
  "id": 4,
  "nome": "Fabio Junior Rodrigues",
  "email": "fabiojunior@gmail.com",
  "senha": "teste@124"
}

### Obter usuario por id
GET {{host}}/usuarios/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ3ZWxsZW4ucm9jaGFAZ21haWwuY29tIiwiaWF0IjoxNzI5Mzg2NzAzLCJleHAiOjE3Mjk0NzMxMDN9.8VS3Buf5M-UiRCZF-PyroF4h5xRDgaoqiphYezISW81kEQNvoebRXcEoUUDQf1-YNu-8t_lafBJYekh9XZ28SQ

### Obter usuario por id
DELETE {{host}}/usuarios/4
Content-Type: application/json