name: Deploy to Elastic Beanstalk - Backend

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      EB_BACKEND_ENV: aroma-delivery-env

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for Maven Wrapper
        run: chmod +x ./mvnw

      - name: Build backend
        working-directory: .
        run: mvn clean install -DskipTests

      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: aromadelivery
          environment_name: aromadelivery-env-1
          version_label: "app-${{ steps.format-time.outputs.replaced }}"
          region: us-east-1
          deployment_package: target/aroma-delivery-0.0.1-SNAPSHOT.jar