name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      EB_BACKEND_ENV: Aroma-delivery-env-env
      EB_FRONTEND_ENV: Aroma-delivery-env-env

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Build do Backend
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build backend
        working-directory: .
        run: ./mvnw clean package -DskipTests

      # Deploy do Backend
      - name: Deploy backend to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          zip -j backend.zip target/*.jar
          eb deploy $EB_BACKEND_ENV --staged --profile default --region $AWS_REGION