name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      EB_BACKEND_ENV: aroma-delivery-env

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for Maven Wrapper
        run: chmod +x ./mvnw

      - name: Build backend
        working-directory: .
        run: mvn clean install -DskipTests

#      - name: Install Elastic Beanstalk CLI
#        run: |
#          pip install --upgrade pip
#          pip install awsebcli

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: aroma-delivery-env
          environment_name: aroma-delivery-env-env
          version_label: 12345
          region: us-east-1
          deployment_package: target/aroma-delivery-0.0.1-SNAPSHOT.jar

      # Deploy do Backend
#      - name: Deploy backend to Elastic Beanstalk
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        run: |
#          zip -j backend.zip target/*.jar
#          eb init -p java-21 aroma-delivery-env --region $AWS_REGION
#          eb deploy aroma-delivery-env --staged